import Head from 'next/head'
import HomePage from "./_home";
import Navbar from "../components/navbar";
import Script from "next/script";

export default function Home() {
    return (<div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
            <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />
            {/* eslint-disable-next-line @next/next/no-sync-scripts */}
            <Script src="https://unpkg.com/aos@2.3.1/dist/aos.js" />
        </Head>
        <Navbar />
        <main>
            <HomePage/>
        </main>

        <footer>

        </footer>
        <script>
            AOS.init()
        </script>
    </div>)
}
