import Head from 'next/head'
import HomePage from "./_home";
import Navbar from "../components/navbar";
import Script from "next/script";
import {ToastContainer} from "react-toastify";
import {logo_svg} from "../public/Logo.svg";

export default function Home() {
    return (<div>
        <Head>
            <title>Comston Technologies</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href={logo_svg}/>
            <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet"/>
            {/* eslint-disable-next-line @next/next/no-sync-scripts */}
        </Head>
        <Navbar/>
        <main>
            <ToastContainer/>
            <HomePage/>
        </main>

        <footer>

        </footer>
        <Script src="https://unpkg.com/aos@2.3.1/dist/aos.js"/>
        <Script src="https://player.vimeo.com/api/player.js"/>
        <script>
            AOS.init()
        </script>
    </div>)
}
