import Head from 'next/head'
import HomePage from "./_home";
import Navbar from "../components/navbar";

export default function Home() {
    return (<div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>
        </Head>
        <Navbar />
        <main>
            <HomePage/>
        </main>

        <footer>

        </footer>
    </div>)
}
